/* eslint-disable prettier/prettier */
// Generated by https://quicktype.io

export interface Post {
  userId: number;
  id?:     number;
  title:  string;
  body:   string;
}

export interface NewPost {
  title:  string;
  body:   string;
}